export const FILM_LIST_REQUEST = 'FILM_LIST_REQUEST';
export const FILM_LIST_SUCCESS = 'FILM_LIST_SUCCESS';
export const FILM_LIST_FAIL = 'FILM_LIST_FAIL';

export const FILM_DETAILS_REQUEST = 'FILM_DETAILS_REQUEST';
export const FILM_DETAILS_SUCCESS = 'FILM_DETAILS_SUCCESS';
export const FILM_DETAILS_FAIL = 'FILM_DETAILS_FAIL';

export const FILM_CREATE_REQUEST = 'FILM_CREATE_REQUEST';
export const FILM_CREATE_SUCCESS = 'FILM_CREATE_SUCCESS';
export const FILM_CREATE_FAIL = 'FILM_CREATE_FAIL';
export const FILM_CREATE_RESET = 'FILM_CREATE_RESET';

export const FILM_UPDATE_REQUEST = 'FILM_UPDATE_REQUEST';
export const FILM_UPDATE_SUCCESS = 'FILM_UPDATE_SUCCESS';
export const FILM_UPDATE_FAIL = 'FILM_UPDATE_FAIL';
export const FILM_UPDATE_RESET = 'FILM_UPDATE_RESET';

export const FILM_DELETE_REQUEST = 'FILM_DELETE_REQUEST';
export const FILM_DELETE_SUCCESS = 'FILM_DELETE_SUCCESS'
export const FILM_DELETE_FAIL = 'FILM_DELETE_FAIL'
export const FILM_DELETE_RESET = 'FILM_DELETE_RESET'

export const FILM_GENRE_LIST_REQUEST = "FILM_GENRE_LIST_REQUEST";
export const FILM_GENRE_LIST_SUCCESS = "FILM_GENRE_LIST_SUCCESS";
export const FILM_GENRE_LIST_FAIL = "FILM_GENRE_LIST_FAIL";

export const FILM_REVIEW_REQUEST = 'FILM_REVIEW_REQUEST';
export const FILM_REVIEW_SUCCESS = 'FILM_REVIEW_SUCCESS';
export const FILM_REVIEW_FAIL = 'FILM_REVIEW_FAIL';
export const FILM_REVIEW_RESET = 'FILM_REVIEW_RESET';
